version: '3'
services:
  scribr:
    image: scribr-app
    environment:
      GITHUB_ID: $GITHUB_ID
      GITHUB_SECRET: $GITHUB_SECRET
      DATABASE_URL: $DATABASE_URL
      JWT_SECRET: $JWT_SECRET
      NEXT_PUBLIC_API_HOST: $NEXT_PUBLIC_API_HOST
      NEXTAUTH_URL: $NEXTAUTH_URL
    ports:
      - '80:80'
